service: automlops-stack

frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: eu-west-2 # ${env:AWS_REGION, 'eu-west-2'}
  deploymentBucket:
    name: ${ssm:mlops-eu-west-2-dev-serverless-deployment}

custom:
  ecrRepository: ${file(./parameters.yml):ecrRepository}

# Configuration validation: 'error' (fatal error), 'warn' (logged to the output) or 'off' (default: warn)
# See https://www.serverless.com/framework/docs/configuration-validation
configValidationMode: error
# 'warn' reports deprecations on the go, 'error' will result with an exception being thrown on first approached deprecation
deprecationNotificationMode: warn:summary

functions:
  dataPreProcessing:
    name: MLOpsDataPreProcessing
    image: ${self:custom.ecrRepository}/mlops-data-preprocessing:${env:DATA_PREPROCESSING_VERSION}
    environment:
      PREPROCESSED_INPUT_BUCKET_NAME: ${ssm:mlops-eu-west-2-dev-automl-data}
      PREPROCESSED_OUTPUT_BUCKET_NAME: ${ssm:mlops-eu-west-2-dev-data}
    iamRoleStatementsName: DataPreProcessingRole
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:DeleteObject
          - s3:DeleteObjectVersion
          - s3:GetObjectVersionTagging
          - s3:ListBucket
          - s3:ListBucketVersions
          - s3:PutObject
        Resource:
          - ${ssm:mlops-eu-west-2-dev-automl-data-arn}
          - ${ssm:mlops-eu-west-2-dev-automl-data-arn}/*
          - ${ssm:mlops-eu-west-2-dev-data-arn}
          - ${ssm:mlops-eu-west-2-dev-data-arn}/*
      - Effect: "Allow"
        Action:
          - ksm:GenerateDataKey
          - kms:Decrypt
        Resource:
          - "${ssm:mlops-eu-west-2-dev-automl-data-kms-key-arn}"
          - "${ssm:mlops-eu-west-2-dev-data-kms-key-arn}"
