service: automlops-stack

frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: eu-west-2 # ${env:AWS_REGION, 'eu-west-2'}
  deploymentBucket:
    name: ${ssm:mlops-eu-west-2-dev-serverless-deployment} # Bucket create via Terraform.

custom:
  ecrRepository: ${file(./parameters.yml):ecrRepository}

# Configuration validation: 'error' (fatal error), 'warn' (logged to the output) or 'off' (default: warn)
# See https://www.serverless.com/framework/docs/configuration-validation
configValidationMode: error
# 'warn' reports deprecations on the go, 'error' will result with an exception being thrown on first approached deprecation
deprecationNotificationMode: warn:summary

functions:
  dataPreProcessing:
    name: MLOpsDataPreProcessing
    image: ${self:custom.ecrRepository}/mlops-data-preprocessing:${env:DATA_PREPROCESSING_VERSION}
    environment:
      PREPROCESSED_INPUT_BUCKET_NAME: ${ssm:mlops-eu-west-2-dev-data}
      PREPROCESSED_OUTPUT_BUCKET_NAME: ${ssm:mlops-eu-west-2-dev-automl-data}
    events:
      - s3:
          bucket: ${ssm:mlops-eu-west-2-dev-data}
          event: s3:ObjectCreated:*
          rules:
            - prefix: data/
            - suffix: .csv
          existing: true # Bucket created via Terraform
    iamRoleStatementsName: DataPreProcessingRole
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:DeleteObject
          - s3:DeleteObjectVersion
          - s3:GetObject
          - s3:GetObjectTagging
          - s3:GetObjectVersionTagging
          - s3:ListBucket
          - s3:ListBucketVersions
          - s3:PutObject
          - s3:PutObjectTagging
        Resource:
          - ${ssm:mlops-eu-west-2-dev-automl-data-arn}
          - ${ssm:mlops-eu-west-2-dev-automl-data-arn}/*
          - ${ssm:mlops-eu-west-2-dev-data-arn}
          - ${ssm:mlops-eu-west-2-dev-data-arn}/*
      - Effect: "Allow"
        Action:
          - kms:GenerateDataKey
          - kms:Decrypt
        Resource:
          - "${ssm:mlops-eu-west-2-dev-automl-data-kms-key-arn}"
          - "${ssm:mlops-eu-west-2-dev-data-kms-key-arn}"

  modelTraining:
    name: MLOpsModelTraining
    image: ${self:custom.ecrRepository}/mlops-model-training:${env:MODEL_TRAINING_VERSION}
    environment:
      PREPROCESSED_OUTPUT_BUCKET_NAME: ${ssm:mlops-eu-west-2-dev-automl-data}
      MODEL_OUTPUT_BUCKET_NAME: ${ssm:mlops-eu-west-2-dev-model-output}
    events:
      - s3:
          bucket: ${ssm:mlops-eu-west-2-dev-automl-data}
          event: s3:ObjectCreated:*
          rules:
            - prefix: automl/
            - suffix: .csv
          existing: true # Bucket created via Terraform
    iamRoleStatementsName: ModelTrainingRole
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:GetObject
          - s3:GetObjectTagging
          - s3:GetObjectVersionTagging
          - s3:ListBucket
          - s3:ListBucketVersions
          - s3:PutObject
          - s3:PutObjectTagging
        Resource:
          - ${ssm:mlops-eu-west-2-dev-automl-data-arn}
          - ${ssm:mlops-eu-west-2-dev-automl-data-arn}/*
          - ${ssm:mlops-eu-west-2-dev-model-output-arn}
          - ${ssm:mlops-eu-west-2-dev-model-output-arn}/*
      - Effect: "Allow"
        Action:
          - kms:GenerateDataKey
          - kms:Decrypt
        Resource:
          - "${ssm:mlops-eu-west-2-dev-automl-data-kms-key-arn}"
          - "${ssm:mlops-eu-west-2-dev-model-output-kms-key-arn}"
      - Effect: "Allow"
        Action:
          - iam:GetRole
          - iam:PassRole
        Resource:
          - "${ssm:mlops-eu-west-2-dev-sagemaker-role-arn}"
      - Effect: "Allow"
        Action:
          - sagemaker:CreateTrainingJob
        Resource:
          - "arn:aws:sagemaker:${aws:region}:${aws:accountId}:training-job/xgboost*"

  modelDeployment:
    name: MLOpsModelDeployment
    image: ${self:custom.ecrRepository}/mlops-model-deployment:${env:MODEL_DEPLOYMENT_VERSION}
    environment:
      MODEL_OUTPUT_BUCKET_NAME: ${ssm:mlops-eu-west-2-dev-model-output}
      SAGEMAKER_ROLE_ARN: ${ssm:mlops-eu-west-2-dev-sagemaker-role-arn}
    events:
      - s3:
          bucket: ${ssm:mlops-eu-west-2-dev-model-output}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .tar.gz
          existing: true # Bucket created via Terraform
    iamRoleStatementsName: ModelDeploymentRole
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - iam:GetRole
          - iam:PassRole
        Resource:
          - "${ssm:mlops-eu-west-2-dev-sagemaker-role-arn}"
      - Effect: "Allow"
        Action:
          - s3:GetObject
        Resource:
          - ${ssm:mlops-eu-west-2-dev-model-output-arn}
          - ${ssm:mlops-eu-west-2-dev-model-output-arn}/*
      - Effect: "Allow"
        Action:
          - kms:GenerateDataKey
          - kms:Decrypt
        Resource:
          - "${ssm:mlops-eu-west-2-dev-model-output-kms-key-arn}"
      - Effect: "Allow"
        Action:
          - sagemaker:AddTags
          - sagemaker:CreateEndpoint
          - sagemaker:CreateEndpointConfig
          - sagemaker:CreateModel
        Resource:
          - "arn:aws:sagemaker:${aws:region}:${aws:accountId}:endpoint-config/xgboost*"
          - "arn:aws:sagemaker:${aws:region}:${aws:accountId}:endpoint/xgboost*"
          - "arn:aws:sagemaker:${aws:region}:${aws:accountId}:model/xgboost*"
