name: "💥 Serverless remove all resources"

permissions:
  contents: read

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

jobs:
  remove:
    name: "remove"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: "Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: "Serverless remove"
        uses: serverless/github-action@189dd6854a3b12ecff4a02c49351779f919933ca
        with:
          args: remove
